name = "coinbase-rank-tracker"
main = "src/index.js"
compatibility_date = "2024-01-01"

# KV Namespace binding
kv_namespaces = [
  { binding = "RANK_STORE", id = "YOUR_KV_ID_HERE" }
]

# Cron trigger for every 6 hours
[triggers]
crons = ["0 */6 * * *"]